export const mockData = [
  {
    _id: "1",
    nombre: "John Doe",
    partido: "Party A",
    partido_para_filtro: "Party A",
    genero: "Male",
    cargo_para_filtro: "Position A",
    cargo: "Position A",
    institucion: "Institution A",
    ccaa: "CCAA A",
    sueldobase_sueldo: 1000,
    complementos_sueldo: 200,
    pagasextra_sueldo: 50,
    otrasdietaseindemnizaciones_sueldo: 100,
    trienios_sueldo: 150,
    retribucionmensual: 1500,
    retribucionanual: 18000,
    observaciones: "Observation A",
  },
  {
    _id: "2",
    nombre: "Jane Doe",
    partido: "Party B",
    partido_para_filtro: "Party B",
    genero: "Female",
    cargo_para_filtro: "Position B",
    cargo: "Position B",
    institucion: "Institution B",
    ccaa: "CCAA B",
    sueldobase_sueldo: 2000,
    complementos_sueldo: 300,
    pagasextra_sueldo: 100,
    otrasdietaseindemnizaciones_sueldo: 150,
    trienios_sueldo: 200,
    retribucionmensual: 2750,
    retribucionanual: 33000,
    observaciones: "Observation B",
  },
];
