/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PoliticiansImport } from './routes/politicians'

// Create Virtual Routes

const StatisticsLazyImport = createFileRoute('/statistics')()

// Create/Update Routes

const StatisticsLazyRoute = StatisticsLazyImport.update({
  path: '/statistics',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/statistics.lazy').then((d) => d.Route))

const PoliticiansRoute = PoliticiansImport.update({
  path: '/politicians',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/politicians': {
      preLoaderRoute: typeof PoliticiansImport
      parentRoute: typeof rootRoute
    }
    '/statistics': {
      preLoaderRoute: typeof StatisticsLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  PoliticiansRoute,
  StatisticsLazyRoute,
])

/* prettier-ignore-end */
